// volume indicators

import { IndicatorType } from "./";
// cycle indicators
import {
	HtDcperiodConfig,
	HtDcphaseConfig,
	HtPhasorConfig,
	HtSineConfig,
	HtTrendmodeConfig,
} from "./config/cycle";
// momentum indicators
import {
	ADXConfig,
	ADXRConfig,
	APOConfig,
	AROONConfig,
	AROONOSCConfig,
	BOPConfig,
	CCIConfig,
	CMOConfig,
	DXConfig,
	MACDConfig,
	MACDEXTConfig,
	MACDFIXConfig,
	MFIConfig,
	MinusDiConfig,
	MinusDmConfig,
	MOMConfig,
	PlusDiConfig,
	PlusDmConfig,
	PPOConfig,
	ROCConfig,
	ROCPConfig,
	ROCR100Config,
	ROCRConfig,
	RSIConfig,
	STOCHConfig,
	STOCHFConfig,
	STOCHRSIConfig,
	TRIXConfig,
	ULTOSCConfig,
	WILLRConfig,
} from "./config/momentum";
// overlap indicators
import {
	BBANDSConfig,
	DEMAConfig,
	EMAConfig,
	HtTrendlineConfig,
	KAMAConfig,
	MAConfig,
	MAMAConfig,
	MIDPOINTConfig,
	MIDPRICEConfig,
	SARConfig,
	SAREXTConfig,
	SMAConfig,
	T3Config,
	TEMAConfig,
	TRIMAConfig,
	WMAConfig,
} from "./config/overlap";
// pattern recognition indicators
import {
	CDL2CROWSConfig,
	CDL3BLACKCROWSConfig,
	CDL3INSIDEConfig,
	CDL3LINESTRIKEConfig,
	CDL3OUTSIDEConfig,
	CDL3STARSINSOUTHConfig,
	CDL3WHITESOLDIERSConfig,
	CDLABANDONEDBABYConfig,
	CDLADVANCEBLOCKConfig,
	CDLBELTHOLDConfig,
	CDLBREAKAWAYConfig,
	CDLCLOSINGMARUBOZUConfig,
	CDLCONCEALBABYSWALLConfig,
	CDLCOUNTERATTACKConfig,
	CDLDARKCLOUDCOVERConfig,
	CDLDOJIConfig,
	CDLDOJISTARConfig,
	CDLDRAGONFLYDOJIConfig,
	CDLENGULFINGConfig,
	CDLEVENINGDOJISTARConfig,
	CDLEVENINGSTARConfig,
	CDLGAPSIDESIDEWHITEConfig,
	CDLGRAVESTONEDOJIConfig,
	CDLHAMMERConfig,
	CDLHANGINGMANConfig,
	CDLHARAMIConfig,
	CDLHARAMICROSSConfig,
	CDLHIGHWAVEConfig,
	CDLHIKKAKEConfig,
	CDLHIKKAKEMODConfig,
	CDLHOMINGPIGEONConfig,
	CDLIDENTICAL3CROWSConfig,
	CDLINNECKConfig,
	CDLINVERTEDHAMMERConfig,
	CDLKICKINGBYLENGTHConfig,
	CDLKICKINGConfig,
	CDLLADDERBOTTOMConfig,
	CDLLONGLEGGEDDOJIConfig,
	CDLLONGLINEConfig,
	CDLMARUBOZUConfig,
	CDLMATCHINGLOWConfig,
	CDLMATHOLDConfig,
	CDLMORNINGDOJISTARConfig,
	CDLMORNINGSTARConfig,
	CDLONNECKConfig,
	CDLPIERCINGConfig,
	CDLRICKSHAWMANConfig,
	CDLRISEFALL3METHODSConfig,
	CDLSEPARATINGLINESConfig,
	CDLSHOOTINGSTARConfig,
	CDLSHORTLINEConfig,
	CDLSPINNINGTOPConfig,
	CDLSTALLEDPATTERNConfig,
	CDLSTICKSANDWICHConfig,
	CDLTAKURIConfig,
	CDLTASUKIGAPConfig,
	CDLTHRUSTINGConfig,
	CDLTRISTARConfig,
	CDLUNIQUE3RIVERConfig,
	CDLUPSIDEGAP2CROWSConfig,
	CDLXSIDEGAP3METHODSConfig,
} from "./config/pattern_recognition";
// price transform indicators
import {
	AVGPRICEConfig,
	MEDPRICEConfig,
	TYPPRICEConfig,
	WCLPRICEConfig,
} from "./config/price_transform";
// volatility indicators
import { ATRConfig, NATRConfig, TRANGEConfig } from "./config/volatility";
import { ADConfig, ADOSCConfig, OBVConfig } from "./config/volume";
import type { IndicatorConfig } from "./indicator-config";

// 配置映射，支持部分指标类型
export const INDICATOR_CONFIG_MAP: Partial<
	Record<IndicatorType, IndicatorConfig>
> = {
	// overlap indicators
	[IndicatorType.MA]: MAConfig,
	[IndicatorType.SMA]: SMAConfig,
	[IndicatorType.EMA]: EMAConfig,
	[IndicatorType.DEMA]: DEMAConfig,
	[IndicatorType.WMA]: WMAConfig,
	[IndicatorType.BBANDS]: BBANDSConfig,
	// [IndicatorType.ACCBANDS]: AccBandsConfig,
	[IndicatorType.HT_TRENDLINE]: HtTrendlineConfig,
	[IndicatorType.KAMA]: KAMAConfig,
	[IndicatorType.MAMA]: MAMAConfig,
	[IndicatorType.MIDPOINT]: MIDPOINTConfig,
	[IndicatorType.MIDPRICE]: MIDPRICEConfig,
	[IndicatorType.SAR]: SARConfig,
	[IndicatorType.SAREXT]: SAREXTConfig,
	[IndicatorType.T3]: T3Config,
	[IndicatorType.TEMA]: TEMAConfig,
	[IndicatorType.TRIMA]: TRIMAConfig,

	// volume indicators
	[IndicatorType.AD]: ADConfig,
	[IndicatorType.ADOSC]: ADOSCConfig,
	[IndicatorType.OBV]: OBVConfig,

	// volatility indicators
	[IndicatorType.ATR]: ATRConfig,
	[IndicatorType.NATR]: NATRConfig,
	[IndicatorType.TRANGE]: TRANGEConfig,

	// momentum indicators
	[IndicatorType.MACD]: MACDConfig,
	[IndicatorType.MACDEXT]: MACDEXTConfig,
	[IndicatorType.MACDFIX]: MACDFIXConfig,
	[IndicatorType.RSI]: RSIConfig,
	[IndicatorType.ADX]: ADXConfig,
	[IndicatorType.ADXR]: ADXRConfig,
	[IndicatorType.APO]: APOConfig,
	[IndicatorType.AROON]: AROONConfig,
	[IndicatorType.AROONOSC]: AROONOSCConfig,
	[IndicatorType.BOP]: BOPConfig,
	[IndicatorType.CCI]: CCIConfig,
	[IndicatorType.CMO]: CMOConfig,
	[IndicatorType.DX]: DXConfig,
	[IndicatorType.MFI]: MFIConfig,
	[IndicatorType.MINUS_DI]: MinusDiConfig,
	[IndicatorType.MINUS_DM]: MinusDmConfig,
	[IndicatorType.MOM]: MOMConfig,
	[IndicatorType.PLUS_DI]: PlusDiConfig,
	[IndicatorType.PLUS_DM]: PlusDmConfig,
	[IndicatorType.PPO]: PPOConfig,
	[IndicatorType.ROC]: ROCConfig,
	[IndicatorType.ROCP]: ROCPConfig,
	[IndicatorType.ROCR]: ROCRConfig,
	[IndicatorType.ROCR100]: ROCR100Config,
	[IndicatorType.STOCH]: STOCHConfig,
	[IndicatorType.STOCHF]: STOCHFConfig,
	[IndicatorType.STOCHRSI]: STOCHRSIConfig,
	[IndicatorType.TRIX]: TRIXConfig,
	[IndicatorType.ULTOSC]: ULTOSCConfig,
	[IndicatorType.WILLR]: WILLRConfig,

	// cycle indicators
	[IndicatorType.HT_DCPERIOD]: HtDcperiodConfig,
	[IndicatorType.HT_DCPHASE]: HtDcphaseConfig,
	[IndicatorType.HT_PHASOR]: HtPhasorConfig,
	[IndicatorType.HT_SINE]: HtSineConfig,
	[IndicatorType.HT_TRENDMODE]: HtTrendmodeConfig,

	// price transform indicators
	[IndicatorType.AVGPRICE]: AVGPRICEConfig,
	[IndicatorType.MEDPRICE]: MEDPRICEConfig,
	[IndicatorType.TYPPRICE]: TYPPRICEConfig,
	[IndicatorType.WCLPRICE]: WCLPRICEConfig,

	// pattern recognition indicators
	[IndicatorType.CDL2CROWS]: CDL2CROWSConfig,
	[IndicatorType.CDL3BLACKCROWS]: CDL3BLACKCROWSConfig,
	[IndicatorType.CDL3INSIDE]: CDL3INSIDEConfig,
	[IndicatorType.CDL3LINESTRIKE]: CDL3LINESTRIKEConfig,
	[IndicatorType.CDL3OUTSIDE]: CDL3OUTSIDEConfig,
	[IndicatorType.CDL3STARSINSOUTH]: CDL3STARSINSOUTHConfig,
	[IndicatorType.CDL3WHITESOLDIERS]: CDL3WHITESOLDIERSConfig,
	[IndicatorType.CDLABANDONEDBABY]: CDLABANDONEDBABYConfig,
	[IndicatorType.CDLADVANCEBLOCK]: CDLADVANCEBLOCKConfig,
	[IndicatorType.CDLBELTHOLD]: CDLBELTHOLDConfig,
	[IndicatorType.CDLBREAKAWAY]: CDLBREAKAWAYConfig,
	[IndicatorType.CDLCLOSINGMARUBOZU]: CDLCLOSINGMARUBOZUConfig,
	[IndicatorType.CDLCONCEALBABYSWALL]: CDLCONCEALBABYSWALLConfig,
	[IndicatorType.CDLCOUNTERATTACK]: CDLCOUNTERATTACKConfig,
	[IndicatorType.CDLDARKCLOUDCOVER]: CDLDARKCLOUDCOVERConfig,
	[IndicatorType.CDLDOJI]: CDLDOJIConfig,
	[IndicatorType.CDLDOJISTAR]: CDLDOJISTARConfig,
	[IndicatorType.CDLDRAGONFLYDOJI]: CDLDRAGONFLYDOJIConfig,
	[IndicatorType.CDLENGULFING]: CDLENGULFINGConfig,
	[IndicatorType.CDLEVENINGDOJISTAR]: CDLEVENINGDOJISTARConfig,
	[IndicatorType.CDLEVENINGSTAR]: CDLEVENINGSTARConfig,
	[IndicatorType.CDLGAPSIDESIDEWHITE]: CDLGAPSIDESIDEWHITEConfig,
	[IndicatorType.CDLGRAVESTONEDOJI]: CDLGRAVESTONEDOJIConfig,
	[IndicatorType.CDLHAMMER]: CDLHAMMERConfig,
	[IndicatorType.CDLHANGINGMAN]: CDLHANGINGMANConfig,
	[IndicatorType.CDLHARAMI]: CDLHARAMIConfig,
	[IndicatorType.CDLHARAMICROSS]: CDLHARAMICROSSConfig,
	[IndicatorType.CDLHIGHWAVE]: CDLHIGHWAVEConfig,
	[IndicatorType.CDLHIKKAKE]: CDLHIKKAKEConfig,
	[IndicatorType.CDLHIKKAKEMOD]: CDLHIKKAKEMODConfig,
	[IndicatorType.CDLHOMINGPIGEON]: CDLHOMINGPIGEONConfig,
	[IndicatorType.CDLIDENTICAL3CROWS]: CDLIDENTICAL3CROWSConfig,
	[IndicatorType.CDLINNECK]: CDLINNECKConfig,
	[IndicatorType.CDLINVERTEDHAMMER]: CDLINVERTEDHAMMERConfig,
	[IndicatorType.CDLKICKING]: CDLKICKINGConfig,
	[IndicatorType.CDLKICKINGBYLENGTH]: CDLKICKINGBYLENGTHConfig,
	[IndicatorType.CDLLADDERBOTTOM]: CDLLADDERBOTTOMConfig,
	[IndicatorType.CDLLONGLEGGEDDOJI]: CDLLONGLEGGEDDOJIConfig,
	[IndicatorType.CDLLONGLINE]: CDLLONGLINEConfig,
	[IndicatorType.CDLMARUBOZU]: CDLMARUBOZUConfig,
	[IndicatorType.CDLMATCHINGLOW]: CDLMATCHINGLOWConfig,
	[IndicatorType.CDLMATHOLD]: CDLMATHOLDConfig,
	[IndicatorType.CDLMORNINGDOJISTAR]: CDLMORNINGDOJISTARConfig,
	[IndicatorType.CDLMORNINGSTAR]: CDLMORNINGSTARConfig,
	[IndicatorType.CDLONNECK]: CDLONNECKConfig,
	[IndicatorType.CDLPIERCING]: CDLPIERCINGConfig,
	[IndicatorType.CDLRICKSHAWMAN]: CDLRICKSHAWMANConfig,
	[IndicatorType.CDLRISEFALL3METHODS]: CDLRISEFALL3METHODSConfig,
	[IndicatorType.CDLSEPARATINGLINES]: CDLSEPARATINGLINESConfig,
	[IndicatorType.CDLSHOOTINGSTAR]: CDLSHOOTINGSTARConfig,
	[IndicatorType.CDLSHORTLINE]: CDLSHORTLINEConfig,
	[IndicatorType.CDLSPINNINGTOP]: CDLSPINNINGTOPConfig,
	[IndicatorType.CDLSTALLEDPATTERN]: CDLSTALLEDPATTERNConfig,
	[IndicatorType.CDLSTICKSANDWICH]: CDLSTICKSANDWICHConfig,
	[IndicatorType.CDLTAKURI]: CDLTAKURIConfig,
	[IndicatorType.CDLTASUKIGAP]: CDLTASUKIGAPConfig,
	[IndicatorType.CDLTHRUSTING]: CDLTHRUSTINGConfig,
	[IndicatorType.CDLTRISTAR]: CDLTRISTARConfig,
	[IndicatorType.CDLUNIQUE3RIVER]: CDLUNIQUE3RIVERConfig,
	[IndicatorType.CDLUPSIDEGAP2CROWS]: CDLUPSIDEGAP2CROWSConfig,
	[IndicatorType.CDLXSIDEGAP3METHODS]: CDLXSIDEGAP3METHODSConfig,
};
