import React, { useCallback, useEffect } from "react";
import { Button } from "@/components/ui/button";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from "@/components/ui/dialog";
import type { VariableItem } from "@/hooks/flow/use-strategy-workflow";
import { useStartNodeDataStore } from "@/store/node/use-start-node-data-store";
import useTradingModeStore from "@/store/useTradingModeStore";
import type { NodeType } from "@/types/node/index";
import type {
	GetVariableConfig,
	ResetVariableConfig,
	TimerTrigger,
	ConditionTrigger,
	DataFlowTrigger,
	UpdateOperationType,
	UpdateVariableConfig,
	VariableConfig,
	TriggerConfig,
} from "@/types/node/variable-node";
import {
	getConditionTriggerConfig,
	getDataFlowTriggerConfig,
	getEffectiveTriggerType,
	getTimerTriggerConfig,
} from "@/types/node/variable-node";
import { TradeMode } from "@/types/strategy";
import {
	type CustomVariable,
	getVariableTypeIcon,
	getVariableTypeIconColor,
	SYSTEM_VARIABLE_METADATA,
	SystemVariable,
	VariableValueType,
} from "@/types/variable";
import {
	generateVariableName,
	isDuplicateConfig,
} from "../../../variable-node-utils";
import type { CaseItemInfo } from "./components/case-selector";
import type { SymbolSelectorOption } from "./components/symbol-selector";
import GetVarConfig from "./get-var-config";
import ResetVarConfig from "./reset-var-config";
import UpdateVarConfig from "./update-var-config";
import VarOperateGuide from "./var-operate-guide";
import { getUpdateOperationLabel } from "./variable-setting-dialog-utils";

const buildTriggerConfigFromState = (
	triggerType: "condition" | "timer" | "dataflow",
	options: {
		timerConfig?: TimerTrigger;
		conditionConfig?: ConditionTrigger | null;
		dataflowConfig?: DataFlowTrigger | null;
	},
): TriggerConfig => {
	if (triggerType === "timer") {
		return options.timerConfig
			? { type: "timer", config: options.timerConfig }
			: null;
	}

	if (triggerType === "condition") {
		return options.conditionConfig
			? { type: "condition", config: options.conditionConfig }
			: null;
	}

	if (triggerType === "dataflow") {
		return options.dataflowConfig
			? { type: "dataflow", config: options.dataflowConfig }
			: null;
	}

	return null;
};

interface VariableConfigDialogProps {
	id: string; // 节点id
	isOpen: boolean;
	isEditing: boolean;
	editingConfig?: VariableConfig;
	onOpenChange: (open: boolean) => void;
	onSave: (id: string, config: VariableConfig) => void;
	existingConfigs: VariableConfig[];
	editingIndex: number | null;
	variableItemList: VariableItem[];
	caseItemList: CaseItemInfo[];
	symbolOptions: SymbolSelectorOption[];
	symbolPlaceholder: string;
	symbolEmptyMessage: string;
	isSymbolSelectorDisabled: boolean;
}

const VariableConfigDialog: React.FC<VariableConfigDialogProps> = ({
	id,
	isOpen,
	isEditing,
	editingConfig,
	onOpenChange,
	onSave,
	existingConfigs,
	editingIndex,
	variableItemList,
	caseItemList,
	symbolOptions,
	symbolPlaceholder,
	symbolEmptyMessage,
	isSymbolSelectorDisabled,
}) => {
	// 获取开始节点的配置
	const {
		backtestConfig: startNodeBacktestConfig,
		liveConfig: startNodeLiveConfig,
		// simulateConfig: startNodeSimulateConfig,
	} = useStartNodeDataStore();
	const { tradingMode } = useTradingModeStore();

	// 获取自定义变量列表
	const customVariables = React.useMemo(() => {
		if (tradingMode === TradeMode.BACKTEST) {
			return startNodeBacktestConfig?.customVariables || [];
		} else if (tradingMode === TradeMode.LIVE) {
			return startNodeLiveConfig?.customVariables || [];
		} else {
			return [];
		}
	}, [tradingMode, startNodeBacktestConfig, startNodeLiveConfig]);

	const customVariableOptions = React.useMemo(
		() =>
			customVariables.map((customVar: CustomVariable) => {
				const IconComponent = getVariableTypeIcon(customVar.varValueType);
				const iconColor = getVariableTypeIconColor(customVar.varValueType);

				return {
					value: customVar.varName,
					label: (
						<div className="flex items-center gap-2">
							<IconComponent className={`h-4 w-4 ${iconColor}`} />
							<span>{customVar.varDisplayName}</span>
							<span className="text-xs text-muted-foreground">
								({customVar.varName})
							</span>
						</div>
					),
				};
			}),
		[customVariables],
	);

	// 步骤状态: 1=选择操作类型, 2=配置参数
	const [currentStep, setCurrentStep] = React.useState<1 | 2>(1);

	// 表单状态
	const [varOperation, setVarOperation] = React.useState<
		"get" | "update" | "reset"
	>("get");
	const [symbol, setSymbol] = React.useState<string>("");
	const [variableName, setVariableName] = React.useState<string>("");
	const [variable, setVariable] = React.useState<string>(
		SystemVariable.TOTAL_POSITION_NUMBER,
	);
	const [triggerType, setTriggerType] = React.useState<
		"condition" | "timer" | "dataflow"
	>("condition");
	const [timerConfig, setTimerConfig] = React.useState<TimerTrigger>({
		mode: "interval",
		interval: 1,
		unit: "minute",
	});
	const [isNameAutoGenerated, setIsNameAutoGenerated] =
		React.useState<boolean>(true);
	// update模式的状态
	const [updateOperationType, setUpdateOperationType] =
		React.useState<UpdateOperationType>("set");
	const [updateValue, setUpdateValue] = React.useState<string>("");
	const [updateTriggerType, setUpdateTriggerType] = React.useState<
		"condition" | "timer" | "dataflow"
	>("condition");

	// dataflow模式的状态 - 用于从上游节点选择变量
	const [dataflowNodeId, setDataflowNodeId] = React.useState<string | null>(
		null,
	);
	const [dataflowNodeType, setDataflowNodeType] =
		React.useState<NodeType | null>(null);
	const [dataflowNodeName, setDataflowNodeName] = React.useState<string | null>(
		null,
	);
	const [dataflowHandleId, setDataflowHandleId] = React.useState<string | null>(
		null,
	);
	const [dataflowVariable, setDataflowVariable] = React.useState<string | null>(
		null,
	);
	const [dataflowVariableName, setDataflowVariableName] = React.useState<
		string | null
	>(null);
	const [dataflowVariableId, setDataflowVariableId] = React.useState<
		number | null
	>(null);
	const [dataflowVariableValueType, setDataflowVariableValueType] =
		React.useState<VariableValueType | null>(null);

	// reset模式的状态 - 变量初始值
	const [varInitialValue, setVarInitialValue] = React.useState<
		string | number | boolean | string[]
	>("");

	// get模式的验证状态
	const [isGetConfigValid, setIsGetConfigValid] = React.useState<boolean>(true);

	// get模式的条件触发配置 - 用于选择触发的 case
	const [triggerCase, setTriggerCase] = React.useState<ConditionTrigger | null>(
		null,
	);

	// 用于追踪上一个变量的类型，以便在变量类型改变时清空更新值
	const prevVarValueTypeRef = React.useRef<VariableValueType | null>(null);

	// 根据变量类型和触发方式获取可用的更新操作
	const getAvailableOperations = (
		varValueType: VariableValueType,
		isDataflowMode?: boolean,
	): UpdateOperationType[] => {
		if (
			varValueType === VariableValueType.NUMBER ||
			varValueType === VariableValueType.PERCENTAGE
		) {
			// 数据流模式支持 max 和 min，条件/定时触发模式不支持
			if (isDataflowMode) {
				return ["set", "add", "subtract", "multiply", "divide", "max", "min"];
			}
			return ["set", "add", "subtract", "multiply", "divide"];
		} else if (varValueType === VariableValueType.BOOLEAN) {
			return ["set", "toggle"];
		} else if (varValueType === VariableValueType.ENUM) {
			return ["set", "append", "remove", "clear"];
		} else {
			// STRING, TIME 类型只支持直接赋值
			return ["set"];
		}
	};

	// 生成 Dialog 标题
	const getDialogTitle = (): React.ReactNode => {
		const prefix = isEditing ? "编辑" : "添加";

		// Step 1: 返回基础标题
		if (currentStep === 1) {
			return `${prefix}变量配置`;
		}

		// Step 2: 根据操作类型返回带高亮的标题
		const operationLabels = {
			get: "获取",
			update: "更新",
			reset: "重置",
		};

		const operationLabel = operationLabels[varOperation];

		return (
			<>
				{prefix}
				<span className="font-semibold text-blue-600 px-1 py-0.5 rounded bg-blue-50">
					{operationLabel}
				</span>
				变量配置
			</>
		);
	};

	const resetForm = useCallback(() => {
		setCurrentStep(1);
		setVarOperation("get");
		setSymbol("");
		setVariableName("");
		setVariable(SystemVariable.TOTAL_POSITION_NUMBER);
		setTriggerType("condition");
		setTimerConfig({
			mode: "interval",
			interval: 1,
			unit: "minute",
		});
		setIsNameAutoGenerated(true);
		setUpdateOperationType("set");
		setUpdateValue("");
		setUpdateTriggerType("condition");
		// 重置dataflow相关状态
		setDataflowNodeId(null);
		setDataflowNodeType(null);
		setDataflowNodeName(null);
		setDataflowHandleId(null);
		setDataflowVariable(null);
		setDataflowVariableName(null);
		setDataflowVariableId(null);
		// 重置reset模式状态
		setVarInitialValue("");
		// 重置验证状态
		setIsGetConfigValid(true);
		// 重置条件触发配置
		setTriggerCase(null);
		// 重置变量类型追踪
		prevVarValueTypeRef.current = null;
	}, []);

	// 当切换操作类型时，自动选择合适的默认变量
	React.useEffect(() => {
		if (varOperation === "update" || varOperation === "reset") {
			if (customVariables.length > 0) {
				// 有自定义变量，自动选中第一个
				setVariable(customVariables[0].varName);
			} else {
				// 没有自定义变量，清空变量选择
				setVariable("");
			}
		} else if (varOperation === "get") {
			// 切换到 get 模式时，恢复为默认的系统变量
			setVariable(SystemVariable.TOTAL_POSITION_NUMBER);
			// 重置变量类型追踪
			prevVarValueTypeRef.current = null;
		}
	}, [varOperation, customVariables]);

	// 当变量改变时，检查当前的操作类型是否适用于新变量类型，如果不适用则自动切换
	React.useEffect(() => {
		if (varOperation === "update" && variable) {
			const selectedVar = customVariables.find(
				(v: CustomVariable) => v.varName === variable,
			);
			if (selectedVar) {
				// 检查变量类型是否改变
				const currentVarValueType = selectedVar.varValueType;
				const hasTypeChanged =
					prevVarValueTypeRef.current !== null &&
					prevVarValueTypeRef.current !== currentVarValueType;

				// 如果变量类型改变，清空更新值
				if (hasTypeChanged) {
					setUpdateValue("");
				}

				// 更新ref为当前类型
				prevVarValueTypeRef.current = currentVarValueType;

				const isDataflowMode = updateTriggerType === "dataflow";
				const availableOps = getAvailableOperations(
					selectedVar.varValueType,
					isDataflowMode,
				);
				// 如果当前操作类型不在可用操作列表中，则切换到第一个可用操作
				if (!availableOps.includes(updateOperationType)) {
					setUpdateOperationType(availableOps[0]);
					// 如果切换到 toggle，清空输入值
					if (availableOps[0] === "toggle") {
						setUpdateValue("");
					}
					// 如果切换到 set 且是 BOOLEAN 类型，设置默认值为 "true"
					else if (
						availableOps[0] === "set" &&
						selectedVar.varValueType === VariableValueType.BOOLEAN
					) {
						setUpdateValue("true");
					}
				}
				// 如果操作类型是 set 且变量是 BOOLEAN 类型，且当前值为空，设置默认值
				else if (
					updateOperationType === "set" &&
					selectedVar.varValueType === VariableValueType.BOOLEAN &&
					!updateValue
				) {
					setUpdateValue("true");
				}
			}
		}
	}, [
		variable,
		varOperation,
		customVariables,
		updateOperationType,
		updateValue,
		updateTriggerType,
	]);

	// 当reset模式下变量改变时，更新初始值
	React.useEffect(() => {
		if (varOperation === "reset" && variable) {
			const selectedVar = customVariables.find(
				(v: CustomVariable) => v.varName === variable,
			);
			if (selectedVar) {
				setVarInitialValue(selectedVar.initialValue);
			}
		}
	}, [variable, varOperation, customVariables]);

	// 当对话框打开时重置或恢复状态
	useEffect(() => {
		if (isOpen) {
			if (isEditing && editingConfig) {
				setCurrentStep(2); // 编辑时直接进入配置步骤
				setVarOperation(editingConfig.varOperation);
				setVariable(editingConfig.varName);

				if (editingConfig.varOperation === "get") {
					setSymbol(
						("symbol" in editingConfig ? editingConfig.symbol : null) || "",
					);
					setVariableName(editingConfig.varDisplayName);

					const effectiveTriggerType =
						getEffectiveTriggerType(editingConfig) ?? "condition";
					const existingTimer = getTimerTriggerConfig(editingConfig);
					const existingCondition = getConditionTriggerConfig(editingConfig);

					setTriggerType(effectiveTriggerType);

					if (effectiveTriggerType === "timer") {
						if (existingTimer) {
							setTimerConfig(existingTimer);
						}
						setTriggerCase(null);
					} else if (effectiveTriggerType === "condition") {
						setTriggerCase(existingCondition ?? null);
					}

					setIsNameAutoGenerated(false); // 编辑时不是自动生成的
				} else if (editingConfig.varOperation === "update") {
					setUpdateOperationType(editingConfig.updateOperationType);

					const effectiveUpdateTriggerType =
						getEffectiveTriggerType(editingConfig) ?? "condition";
					const existingTimer = getTimerTriggerConfig(editingConfig);
					const existingCondition = getConditionTriggerConfig(editingConfig);
					const existingDataflow = getDataFlowTriggerConfig(editingConfig);

					setUpdateTriggerType(effectiveUpdateTriggerType);

					if (effectiveUpdateTriggerType === "timer") {
						if (existingTimer) {
							setTimerConfig(existingTimer);
						}
						setTriggerCase(null);
						setUpdateValue(String(editingConfig.updateOperationValue || ""));
					} else if (effectiveUpdateTriggerType === "condition") {
						setTriggerCase(existingCondition ?? null);
						setUpdateValue(String(editingConfig.updateOperationValue || ""));
				} else if (effectiveUpdateTriggerType === "dataflow") {
					if (existingDataflow) {
						setDataflowNodeId(existingDataflow.fromNodeId);
						setDataflowHandleId(existingDataflow.fromHandleId);
						setDataflowVariable(existingDataflow.fromVar);
						setDataflowVariableName(
							existingDataflow.fromVarDisplayName,
						);
						setDataflowVariableId(existingDataflow.fromVarConfigId);
						setDataflowVariableValueType(
							existingDataflow.fromVarValueType,
						);

						const selectedNode = variableItemList.find(
							(item) => item.nodeId === existingDataflow.fromNodeId,
						);
						if (selectedNode) {
							setDataflowNodeType(selectedNode.nodeType);
							setDataflowNodeName(selectedNode.nodeName);
						}
					}
					setTriggerCase(null);
					setUpdateValue("");
				}
				} else {
					const effectiveTriggerType =
						getEffectiveTriggerType(editingConfig) ?? "condition";
					const existingTimer = getTimerTriggerConfig(editingConfig);
					const existingCondition = getConditionTriggerConfig(editingConfig);

					setTriggerType(effectiveTriggerType);

					if (effectiveTriggerType === "timer") {
						if (existingTimer) {
							setTimerConfig(existingTimer);
						}
						setTriggerCase(null);
					} else if (effectiveTriggerType === "condition") {
						setTriggerCase(existingCondition ?? null);
					}

					setVarInitialValue(editingConfig.varInitialValue);
				}
			} else {
				resetForm();
				// 新建时生成默认名称
				const defaultName = generateVariableName(
					SystemVariable.TOTAL_POSITION_NUMBER,
					existingConfigs.length,
					customVariables,
				);
				setVariableName(defaultName);
				setIsNameAutoGenerated(true);
			}
		}
	}, [
		isOpen,
		isEditing,
		editingConfig,
		existingConfigs.length,
	resetForm,
	variableItemList,
	customVariables,
	]);

	// 检查是否存在重复配置
	const isDuplicate = () => {
		return isDuplicateConfig(
			existingConfigs,
			editingIndex,
			symbol,
			variable,
			triggerType,
		);
	};

	// 当变量类型改变时，自动填充变量名称
	const handleVariableTypeChange = (newType: string) => {
		setVariable(newType);

		// 所有模式都使用 generateVariableName 生成带序号的名称
		if (isNameAutoGenerated || !variableName.trim()) {
			const newName = generateVariableName(
				newType,
				existingConfigs.length,
				customVariables,
			);
			setVariableName(newName);
			setIsNameAutoGenerated(true);
		}
	};

	// 当用户手动修改变量名称时，标记为非自动生成
	const handleVariableNameChange = (value: string) => {
		setVariableName(value);
		setIsNameAutoGenerated(false);
	};

	// 处理dataflow节点选择
	const handleDataflowNodeChange = (
		nodeId: string,
		nodeType: NodeType | null,
		nodeName: string,
	) => {
		setDataflowNodeId(nodeId);
		setDataflowNodeType(nodeType);
		setDataflowNodeName(nodeName);
		// 清空变量选择
		setDataflowHandleId(null);
		setDataflowVariable(null);
		setDataflowVariableName(null);
		setDataflowVariableId(null);
		setDataflowVariableValueType(null);
	};

	// 处理dataflow变量选择
	const handleDataflowVariableChange = (
		variableId: number,
		handleId: string,
		variable: string,
		variableName: string,
		variableValueType: VariableValueType,
	) => {
		setDataflowVariableId(variableId);
		setDataflowHandleId(handleId);
		setDataflowVariable(variable);
		setDataflowVariableName(variableName);
		setDataflowVariableValueType(variableValueType);
	};

	const handleSave = () => {
		// 根据操作类型验证不同的必填字段
		if (varOperation === "get") {
			// get模式：变量名必填
			if (!variableName.trim()) {
				return;
			}
			if (isDuplicate()) {
				return;
			}
		} else if (varOperation === "update") {
			// update模式：数据流触发无需输入值；其它触发方式中 toggle 不需要更新值，其余操作需要
			if (
				updateTriggerType !== "dataflow" &&
				updateOperationType !== "toggle" &&
				!updateValue.trim()
			) {
				return;
			}
		} else {
			// reset模式：变量必填
			if (!variable) {
				return;
			}
		}

		const timerConfigData: TimerTrigger | undefined =
			triggerType === "timer" ? timerConfig : undefined;

		console.log("editingConfig", editingConfig);

		// 根据 varOperation 创建对应的配置类型
		let variableConfig: VariableConfig;

		if (varOperation === "get") {
			// 判断是系统变量还是自定义变量
			const isSystemVariable = Object.values(SystemVariable).includes(
				variable as SystemVariable,
			);
			const selectedCustomVar = customVariables.find(
				(v: CustomVariable) => v.varName === variable,
			);

			// 根据变量类型获取相应的元数据
			let varValueType: VariableValueType;
			let varDisplayName: string;

			if (isSystemVariable) {
				// 系统变量
				const metadata = SYSTEM_VARIABLE_METADATA[variable as SystemVariable];
				varValueType = metadata.varValueType;
				varDisplayName = variableName.trim() || metadata.varDisplayName;
			} else if (selectedCustomVar) {
				// 自定义变量
				varValueType = selectedCustomVar.varValueType;
				varDisplayName =
					variableName.trim() || selectedCustomVar.varDisplayName;
			} else {
				// 默认值
				varValueType = VariableValueType.NUMBER;
				varDisplayName = variableName.trim();
			}

			const getConfig: GetVariableConfig = {
				configId: editingConfig?.configId || 0,
				inputHandleId: editingConfig?.inputHandleId || "",
				outputHandleId: editingConfig?.outputHandleId || "",
				varOperation: "get",
				varType: isSystemVariable ? "system" : "custom",
				symbol: symbol || null,
				triggerConfig: buildTriggerConfigFromState(triggerType, {
					timerConfig: timerConfigData,
					conditionConfig: triggerType === "condition" ? triggerCase : null,
				}),
				varDisplayName: varDisplayName,
				varName: variable,
				varValueType: varValueType,
				varValue: 0,
			};
			variableConfig = getConfig;
		} else if (varOperation === "update") {
			// update 模式 - 查找选中的自定义变量信息
			const selectedCustomVar = customVariables.find(
				(v: CustomVariable) => v.varName === variable,
			);

			// 根据触发方式确定 updateOperationValue
			let updateOperationValue: string | number | boolean | string[] | null;
			let updateDataflowTrigger: DataFlowTrigger | null = null;
			if (updateTriggerType === "dataflow") {
				// 数据流模式：保存 DataFlow 对象
				updateDataflowTrigger = {
					fromNodeId: dataflowNodeId || "",
					fromNodeName: dataflowNodeName || "",
					fromHandleId: dataflowHandleId || "",
					fromVar: dataflowVariable || "",
					fromVarDisplayName: dataflowVariableName || "",
					fromVarConfigId: dataflowVariableId || 0,
					fromNodeType: dataflowNodeType || null,
					fromVarValueType: dataflowVariableValueType || null,
				};
				updateOperationValue = null;
			} else {
				// 条件触发模式：保存输入值或布尔值
				updateOperationValue =
					updateOperationType === "toggle" ? true : updateValue;
			}

			const updateConfig: UpdateVariableConfig = {
				configId: editingConfig?.configId || 0,
				inputHandleId: editingConfig?.inputHandleId || "",
				outputHandleId: editingConfig?.outputHandleId || "",
				varOperation: "update",
				updateOperationType: updateOperationType,
				triggerConfig: buildTriggerConfigFromState(updateTriggerType, {
					timerConfig: updateTriggerType === "timer" ? timerConfig : undefined,
					conditionConfig:
						updateTriggerType === "condition" ? triggerCase : null,
					dataflowConfig: updateTriggerType === "dataflow"
						? updateDataflowTrigger
						: null,
				}),
				varType: "custom", // update 模式下只能是自定义变量
				varName: variable,
				varDisplayName: selectedCustomVar?.varDisplayName || variable,
				varValueType:
					selectedCustomVar?.varValueType || VariableValueType.NUMBER,
				updateOperationValue: updateOperationValue,
			};
			variableConfig = updateConfig;
		} else {
			// reset 模式 - 查找选中的自定义变量信息
			const selectedCustomVar = customVariables.find(
				(v: CustomVariable) => v.varName === variable,
			);

			const resetConfig: ResetVariableConfig = {
				configId: editingConfig?.configId || 0,
				inputHandleId: editingConfig?.inputHandleId || "",
				outputHandleId: editingConfig?.outputHandleId || "",
				varOperation: "reset",
				triggerConfig: buildTriggerConfigFromState(triggerType, {
					timerConfig: timerConfigData,
					conditionConfig: triggerType === "condition" ? triggerCase : null,
				}),
				varType: "custom", // reset 模式下只能是自定义变量
				varName: variable,
				varDisplayName: selectedCustomVar?.varDisplayName || variable,
				varValueType:
					selectedCustomVar?.varValueType || VariableValueType.NUMBER,
				varInitialValue: varInitialValue, // 保存初始值
			};
			variableConfig = resetConfig;
		}

		console.log("variableConfig", variableConfig);

		onSave(id, variableConfig);
		onOpenChange(false);
	};

	const handleNextStep = () => {
		setCurrentStep(2);
	};

	const handleBackStep = () => {
		setCurrentStep(1);
	};

	return (
		<Dialog open={isOpen} onOpenChange={onOpenChange}>
			<DialogContent className="sm:max-w-[500px]">
				<DialogHeader>
					<DialogTitle>{getDialogTitle()}</DialogTitle>
					<DialogDescription>
						{currentStep === 1
							? "请选择要执行的操作类型"
							: varOperation === "get"
								? "从系统或自定义变量中获取值，支持条件触发、定时触发和数据流触发。"
								: varOperation === "update"
									? "修改自定义变量的值，支持赋值、运算、切换等操作。"
									: "将自定义变量重置为初始值，可通过条件或定时触发。"}
					</DialogDescription>
				</DialogHeader>
				<div className="flex flex-col gap-4 py-4">
					{currentStep === 1 ? (
						<VarOperateGuide
							value={varOperation}
							onValueChange={(value) =>
								setVarOperation(value as "get" | "update" | "reset")
							}
							onConfirm={handleNextStep}
						/>
					) : (
						<>
							{varOperation === "get" ? (
								<GetVarConfig
									symbol={symbol}
									variableName={variableName}
									variable={variable}
									triggerConfig={buildTriggerConfigFromState(triggerType, {
										timerConfig: triggerType === "timer" ? timerConfig : undefined,
										conditionConfig: triggerType === "condition" ? triggerCase : null,
									})}
									symbolOptions={symbolOptions}
									symbolPlaceholder={symbolPlaceholder}
									symbolEmptyMessage={symbolEmptyMessage}
									isSymbolSelectorDisabled={isSymbolSelectorDisabled}
									customVariables={customVariables}
									caseItemList={caseItemList}
									onSymbolChange={setSymbol}
									onVariableNameChange={handleVariableNameChange}
									onVariableChange={handleVariableTypeChange}
									onTriggerConfigChange={(newConfig) => {
										const newTriggerType = getEffectiveTriggerType({ triggerConfig: newConfig }) ?? "condition";
										const newTimerConfig = getTimerTriggerConfig({ triggerConfig: newConfig });
										const newConditionConfig = getConditionTriggerConfig({ triggerConfig: newConfig });

										setTriggerType(newTriggerType);
										if (newTimerConfig) setTimerConfig(newTimerConfig);
										setTriggerCase(newConditionConfig ?? null);
									}}
									onValidationChange={setIsGetConfigValid}
								/>
							) : varOperation === "update" ? (
								<UpdateVarConfig
									variable={variable}
									updateOperationType={updateOperationType}
									updateValue={updateValue}
									triggerConfig={buildTriggerConfigFromState(updateTriggerType, {
										timerConfig: updateTriggerType === "timer" ? timerConfig : undefined,
										conditionConfig: updateTriggerType === "condition" ? triggerCase : null,
										dataflowConfig: updateTriggerType === "dataflow" ? {
											fromNodeId: dataflowNodeId || "",
											fromNodeName: dataflowNodeName || "",
											fromHandleId: dataflowHandleId || "",
											fromVar: dataflowVariable || "",
											fromVarDisplayName: dataflowVariableName || "",
											fromVarConfigId: dataflowVariableId || 0,
											fromNodeType: dataflowNodeType || null,
											fromVarValueType: dataflowVariableValueType || null,
										} : null,
									})}
									customVariables={customVariables}
									customVariableOptions={customVariableOptions}
									variableItemList={variableItemList}
									caseItemList={caseItemList}
									dataflowNodeId={dataflowNodeId}
									dataflowHandleId={dataflowHandleId}
									dataflowVariable={dataflowVariable}
									dataflowVariableName={dataflowVariableName}
									onVariableChange={setVariable}
									onUpdateOperationTypeChange={setUpdateOperationType}
									onUpdateValueChange={setUpdateValue}
									onTriggerConfigChange={(newConfig) => {
										const newTriggerType = getEffectiveTriggerType({ triggerConfig: newConfig }) ?? "condition";
										const newTimerConfig = getTimerTriggerConfig({ triggerConfig: newConfig });
										const newConditionConfig = getConditionTriggerConfig({ triggerConfig: newConfig });
										const newDataflowConfig = getDataFlowTriggerConfig({ triggerConfig: newConfig });

										setUpdateTriggerType(newTriggerType);
										if (newTimerConfig) setTimerConfig(newTimerConfig);
										setTriggerCase(newConditionConfig ?? null);

										// 更新 dataflow 相关状态
										if (newDataflowConfig) {
											setDataflowNodeId(newDataflowConfig.fromNodeId);
											setDataflowNodeName(newDataflowConfig.fromNodeName);
											setDataflowHandleId(newDataflowConfig.fromHandleId);
											setDataflowVariable(newDataflowConfig.fromVar);
											setDataflowVariableName(newDataflowConfig.fromVarDisplayName);
											setDataflowVariableId(newDataflowConfig.fromVarConfigId);
											setDataflowNodeType(newDataflowConfig.fromNodeType);
											setDataflowVariableValueType(newDataflowConfig.fromVarValueType);
										}
									}}
									onDataflowNodeChange={handleDataflowNodeChange}
									onDataflowVariableChange={handleDataflowVariableChange}
									getAvailableOperations={getAvailableOperations}
									getUpdateOperationLabel={getUpdateOperationLabel}
								/>
							) : (
								<ResetVarConfig
									variable={variable}
									triggerConfig={buildTriggerConfigFromState(triggerType, {
										timerConfig: triggerType === "timer" ? timerConfig : undefined,
										conditionConfig: triggerType === "condition" ? triggerCase : null,
									})}
									customVariables={customVariables}
									customVariableOptions={customVariableOptions}
									caseItemList={caseItemList}
									varInitialValue={varInitialValue}
									onVariableChange={setVariable}
									onTriggerConfigChange={(newConfig) => {
										const newTriggerType = getEffectiveTriggerType({ triggerConfig: newConfig }) ?? "condition";
										const newTimerConfig = getTimerTriggerConfig({ triggerConfig: newConfig });
										const newConditionConfig = getConditionTriggerConfig({ triggerConfig: newConfig });

										setTriggerType(newTriggerType);
										if (newTimerConfig) setTimerConfig(newTimerConfig);
										setTriggerCase(newConditionConfig ?? null);
									}}
								/>
							)}
						</>
					)}
				</div>
				<DialogFooter>
					{currentStep === 1 ? (
						<>
							<Button variant="outline" onClick={() => onOpenChange(false)}>
								取消
							</Button>
							<Button onClick={handleNextStep}>下一步</Button>
						</>
					) : (
						<>
							<Button variant="outline" onClick={handleBackStep}>
								上一步
							</Button>
							<Button
								onClick={handleSave}
								disabled={
									varOperation === "get"
										? !variableName.trim() || isDuplicate() || !isGetConfigValid
										: varOperation === "update"
											? customVariables.length === 0 ||
												!variable ||
												(updateTriggerType === "condition" &&
													updateOperationType !== "toggle" &&
													!updateValue.trim()) ||
												(updateTriggerType === "dataflow" &&
													(!dataflowNodeId ||
														!dataflowHandleId ||
														!dataflowVariable))
											: customVariables.length === 0 || !variable // reset 模式
								}
							>
								保存
							</Button>
						</>
					)}
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
};

export default VariableConfigDialog;
