import { Clock, Filter, Workflow } from "lucide-react";
import React, { useCallback, useEffect } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ButtonGroup } from "@/components/ui/button-group";
import { Checkbox } from "@/components/ui/checkbox";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/components/ui/select";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import {
	type TimerConfig,
	type VariableConfig,
	type GetVariableConfig,
	type UpdateVariableConfig,
	type UpdateOperationType,
} from "@/types/node/variable-node";
import { SystemVariable, VariableValueType, type CustomVariable, getVariableTypeIcon, getVariableTypeIconColor } from "@/types/variable";
import { useStartNodeDataStore } from "@/store/node/use-start-node-data-store";
import useTradingModeStore from "@/store/useTradingModeStore";
import { TradeMode } from "@/types/strategy";
import SymbolSelector from "./symbol-selector";
import {
	generateVariableName,
	getVariableLabel,
	isDuplicateConfig,
	getUpdateOperationPlaceholder,
} from "./utils";

interface VariableConfigDialogProps {
	id: string; // 节点id
	isOpen: boolean;
	isEditing: boolean;
	editingConfig?: VariableConfig;
	onOpenChange: (open: boolean) => void;
	onSave: (id: string, config: VariableConfig) => void;
	existingConfigs: VariableConfig[];
	editingIndex: number | null;
}

const VariableConfigDialog: React.FC<VariableConfigDialogProps> = ({
	id,
	isOpen,
	isEditing,
	editingConfig,
	onOpenChange,
	onSave,
	existingConfigs,
	editingIndex,
}) => {
	// 获取开始节点的配置
	const {
		backtestConfig: startNodeBacktestConfig,
		liveConfig: startNodeLiveConfig,
		// simulateConfig: startNodeSimulateConfig,
	} = useStartNodeDataStore();
	const { tradingMode } = useTradingModeStore();

	// 获取自定义变量列表
	const customVariables = React.useMemo(() => {
		if (tradingMode === TradeMode.BACKTEST) {
			return startNodeBacktestConfig?.customVariables || [];
		} else if (tradingMode === TradeMode.LIVE) {
			return startNodeLiveConfig?.customVariables || [];
		} else {
			return [];
		}
	}, [tradingMode, startNodeBacktestConfig, startNodeLiveConfig]);

	// 表单状态
	const [varOperation, setVarOperation] = React.useState<"get" | "update">("get");
	const [symbol, setSymbol] = React.useState<string>("");
	const [variableName, setVariableName] = React.useState<string>("");
	const [variable, setVariable] = React.useState<string>(
		SystemVariable.POSITION_NUMBER,
	);
	const [triggerType, setTriggerType] = React.useState<"condition" | "timer">(
		"condition",
	);
	const [timerInterval, setTimerInterval] = React.useState<number>(1);
	const [timerUnit, setTimerUnit] = React.useState<
		"second" | "minute" | "hour" | "day"
	>("minute");
	const [isNameAutoGenerated, setIsNameAutoGenerated] =
		React.useState<boolean>(true);
	// update模式的状态
	const [updateOperationType, setUpdateOperationType] = React.useState<UpdateOperationType>("set");
	const [updateValue, setUpdateValue] = React.useState<string>("");
	const [updateTriggerType, setUpdateTriggerType] = React.useState<"condition" | "dataflow">("condition");

	// 获取更新操作类型的标签
	const getUpdateOperationLabel = (type: UpdateOperationType): string => {
		const labels: Record<UpdateOperationType, string> = {
			set: "=",
			add: "+",
			subtract: "-",
			multiply: "*",
			divide: "÷",
			max: "max",
			min: "min",
			toggle: "toggle",
		};
		return labels[type];
	};

	// 根据变量类型获取可用的更新操作
	const getAvailableOperations = (varValueType: VariableValueType): UpdateOperationType[] => {
		if (varValueType === VariableValueType.NUMBER) {
			return ["set", "add", "subtract", "multiply", "divide", "max", "min"];
		} else if (varValueType === VariableValueType.BOOLEAN) {
			return ["set", "toggle"];
		} else {
			// STRING 类型只支持直接赋值
			return ["set"];
		}
	};

	const resetForm = useCallback(() => {
		setVarOperation("get");
		setSymbol("");
		setVariableName("");
		setVariable(SystemVariable.POSITION_NUMBER);
		setTriggerType("condition");
		setTimerInterval(1);
		setTimerUnit("minute");
		setIsNameAutoGenerated(true);
		setUpdateOperationType("set");
		setUpdateValue("");
		setUpdateTriggerType("condition");
	}, []);

	// 当切换到 update 模式时，自动选中第一个自定义变量（如果有），否则清空变量
	React.useEffect(() => {
		if (varOperation === "update") {
			if (customVariables.length > 0) {
				// 有自定义变量，自动选中第一个
				setVariable(customVariables[0].varName);
			} else {
				// 没有自定义变量，清空变量选择
				setVariable("");
			}
		}
	}, [varOperation, customVariables]);

	// 当变量改变时，检查当前的操作类型是否适用于新变量类型，如果不适用则自动切换
	React.useEffect(() => {
		if (varOperation === "update" && variable) {
			const selectedVar = customVariables.find((v: CustomVariable) => v.varName === variable);
			if (selectedVar) {
				const availableOps = getAvailableOperations(selectedVar.varValueType);
				// 如果当前操作类型不在可用操作列表中，则切换到第一个可用操作
				if (!availableOps.includes(updateOperationType)) {
					setUpdateOperationType(availableOps[0]);
					// 如果切换到 toggle，清空输入值
					if (availableOps[0] === "toggle") {
						setUpdateValue("");
					}
					// 如果切换到 set 且是 BOOLEAN 类型，设置默认值为 "true"
					else if (availableOps[0] === "set" && selectedVar.varValueType === VariableValueType.BOOLEAN) {
						setUpdateValue("true");
					}
				}
				// 如果操作类型是 set 且变量是 BOOLEAN 类型，且当前值为空，设置默认值
				else if (updateOperationType === "set" && selectedVar.varValueType === VariableValueType.BOOLEAN && !updateValue) {
					setUpdateValue("true");
				}
			}
		}
	}, [variable, varOperation, customVariables, updateOperationType]);

	// 当对话框打开时重置或恢复状态
	useEffect(() => {
		if (isOpen) {
			if (isEditing && editingConfig) {
				setVarOperation(editingConfig.varOperation);
				setVariable(editingConfig.varName);

				// 根据操作类型恢复不同的字段
				if (editingConfig.varOperation === "get") {
					setSymbol(editingConfig.symbol || "");
					setVariableName(editingConfig.varDisplayName);
					setTriggerType(editingConfig.varTriggerType);
					if (editingConfig.timerConfig) {
						setTimerInterval(editingConfig.timerConfig.interval);
						setTimerUnit(editingConfig.timerConfig.unit);
					}
					setIsNameAutoGenerated(false); // 编辑时不是自动生成的
				} else {
					// update模式，恢复更新值、操作类型和触发方式
					setUpdateOperationType(editingConfig.updateOperationType);
					setUpdateValue(String(editingConfig.varValue || ""));
					setUpdateTriggerType(editingConfig.varTriggerType);
				}
			} else {
				resetForm();
				// 新建时生成默认名称
				const defaultName = generateVariableName(
					SystemVariable.POSITION_NUMBER,
					existingConfigs.length,
				);
				setVariableName(defaultName);
				setIsNameAutoGenerated(true);
			}
		}
	}, [isOpen, isEditing, editingConfig, existingConfigs.length, resetForm]);

	// 检查是否存在重复配置
	const isDuplicate = () => {
		return isDuplicateConfig(
			existingConfigs,
			editingIndex,
			symbol,
			variable,
			triggerType,
		);
	};

	// 当变量类型改变时，如果名称是自动生成的，则重新生成
	const handleVariableTypeChange = (newType: string) => {
		setVariable(newType);
		if (isNameAutoGenerated || !variableName.trim()) {
			const newName = generateVariableName(newType, existingConfigs.length);
			setVariableName(newName);
			setIsNameAutoGenerated(true);
		}
	};

	// 当用户手动修改变量名称时，标记为非自动生成
	const handleVariableNameChange = (value: string) => {
		setVariableName(value);
		setIsNameAutoGenerated(false);
	};

	const handleSave = () => {
		// 根据操作类型验证不同的必填字段
		if (varOperation === "get") {
			// get模式：变量名必填
			if (!variableName.trim()) {
				return;
			}
			if (isDuplicate()) {
				return;
			}
		} else {
			// update模式：toggle不需要更新值，其他操作需要
			if (updateOperationType !== "toggle" && !updateValue.trim()) {
				return;
			}
		}

		const timerConfig: TimerConfig | undefined =
			varOperation === "get" && triggerType === "timer"
				? {
						interval: timerInterval,
						unit: timerUnit,
					}
				: undefined;

		console.log("editingConfig", editingConfig);

		// 根据 varOperation 创建对应的配置类型
		let variableConfig: VariableConfig;

		if (varOperation === "get") {
			const getConfig: GetVariableConfig = {
				configId: editingConfig?.configId || 0, // 编辑时保持原有id，新增时由主组件设置
				inputHandleId: editingConfig?.inputHandleId || "",
				outputHandleId: editingConfig?.outputHandleId || "",
				varOperation: "get",
				varType: "sys", // 暂时只支持系统变量
				symbol: symbol || null,
				varTriggerType: triggerType as "condition" | "timer",
				timerConfig,
				varDisplayName: variableName.trim(),
				varName: variable,
				varValueType: VariableValueType.NUMBER, // 暂时使用默认值
				varValue: 0, // 默认值，实际运行时会更新
			};
			variableConfig = getConfig;
		} else {
			// update 模式 - 查找选中的自定义变量信息
			const selectedCustomVar = customVariables.find((v: CustomVariable) => v.varName === variable);

			const updateConfig: UpdateVariableConfig = {
				configId: editingConfig?.configId || 0,
				inputHandleId: editingConfig?.inputHandleId || "",
				outputHandleId: editingConfig?.outputHandleId || "",
				varOperation: "update",
				updateOperationType: updateOperationType,
				varTriggerType: updateTriggerType,
				varType: "custom", // update 模式下只能是自定义变量
				varName: variable,
				varValueType: selectedCustomVar?.varValueType || VariableValueType.NUMBER,
				varValue: updateOperationType === "toggle" ? true : updateValue, // toggle使用布尔值，其他使用输入值
			};
			variableConfig = updateConfig;
		}

		console.log("variableConfig", variableConfig);

		onSave(id, variableConfig);
		onOpenChange(false);
	};

	return (
		<Dialog open={isOpen} onOpenChange={onOpenChange}>
			<DialogContent className="sm:max-w-[424px]">
				<DialogHeader>
					<DialogTitle>
						{isEditing ? "编辑变量配置" : "添加变量配置"}
					</DialogTitle>
					<DialogDescription>
						配置变量的参数，包括交易对、触发方式和变量类型。
					</DialogDescription>
				</DialogHeader>
				<div className="flex flex-col gap-4 py-4">
					<div className="flex flex-col gap-2">
						<Label htmlFor="varOperation" className="text-sm font-medium">
							操作类型
						</Label>
						<Select value={varOperation} onValueChange={(value: "get" | "update") => setVarOperation(value)}>
							<SelectTrigger>
								<SelectValue placeholder="选择操作类型" />
							</SelectTrigger>
							<SelectContent>
								<SelectItem value="get">获取变量</SelectItem>
								<SelectItem value="update">更新变量</SelectItem>
							</SelectContent>
						</Select>
					</div>

					{varOperation === "get" ? (
						<>
							<div className="flex flex-col gap-2">
								<Label htmlFor="symbol" className="text-sm font-medium">
									交易对
								</Label>
								<div className="w-full">
									<SymbolSelector
										value={symbol}
										onChange={(value) => {
											setSymbol(value || "");
										}}
										allowEmpty={true}
									/>
								</div>
							</div>

							<div className="flex flex-col gap-2">
								<Label htmlFor="variableName" className="text-sm font-medium">
									变量名称
								</Label>
								<Input
									id="variableName"
									type="text"
									value={variableName}
									onChange={(e) => handleVariableNameChange(e.target.value)}
									placeholder="输入变量名称"
									className="w-full"
								/>
							</div>

							<div className="flex flex-col gap-2">
								<Label htmlFor="variable" className="text-sm font-medium">
									变量
								</Label>
								<Select value={variable} onValueChange={handleVariableTypeChange}>
									<SelectTrigger>
										<SelectValue placeholder="选择变量" />
									</SelectTrigger>
									<SelectContent>
										<SelectItem value={SystemVariable.POSITION_NUMBER}>
											{getVariableLabel(SystemVariable.POSITION_NUMBER)}
										</SelectItem>
										<SelectItem value={SystemVariable.Filled_ORDER_NUMBER}>
											{getVariableLabel(SystemVariable.Filled_ORDER_NUMBER)}
										</SelectItem>
									</SelectContent>
								</Select>
							</div>

							<div className="space-y-1">
								<Label className="text-sm font-medium">触发方式</Label>
								<div className="flex items-center space-x-6 pt-1">
									<div className="flex items-center space-x-2">
										<Checkbox
											id="condition-trigger"
											checked={triggerType === "condition"}
											onCheckedChange={(checked) => {
												if (checked) {
													setTriggerType("condition");
												}
											}}
										/>
										<Label
											htmlFor="condition-trigger"
											className="text-sm cursor-pointer flex items-center"
										>
											<Filter className="h-3.5 w-3.5 mr-1 text-orange-500" />
											条件触发
										</Label>
									</div>
									<div className="flex items-center space-x-2">
										<Checkbox
											id="timer-trigger"
											checked={triggerType === "timer"}
											onCheckedChange={(checked) => {
												if (checked) {
													setTriggerType("timer");
												}
											}}
										/>
										<Label
											htmlFor="timer-trigger"
											className="text-sm cursor-pointer flex items-center"
										>
											<Clock className="h-3.5 w-3.5 mr-1 text-blue-500" />
											定时触发
										</Label>
									</div>
								</div>
							</div>

							{triggerType === "timer" && (
								<div className="space-y-1">
									<Label className="text-sm font-medium">定时配置</Label>
									<div className="flex items-center space-x-2">
										<Input
											type="number"
											min="1"
											step="1"
											value={timerInterval}
											onChange={(e) =>
												setTimerInterval(parseInt(e.target.value) || 1)
											}
											className="h-8 w-20"
										/>
										<Select
											value={timerUnit}
											onValueChange={(
												value: "second" | "minute" | "hour" | "day",
											) => setTimerUnit(value)}
										>
											<SelectTrigger className="h-8 flex-1">
												<SelectValue placeholder="选择时间单位" />
											</SelectTrigger>
											<SelectContent>
												<SelectItem value="second">秒</SelectItem>
												<SelectItem value="minute">分钟</SelectItem>
												<SelectItem value="hour">小时</SelectItem>
												<SelectItem value="day">天</SelectItem>
											</SelectContent>
										</Select>
									</div>
									<div className="flex flex-wrap gap-2 mt-2">
										<Badge
											variant="outline"
											className="bg-blue-50 text-blue-800 cursor-pointer hover:bg-blue-100"
											onClick={() => {
												setTimerInterval(1);
												setTimerUnit("second");
											}}
										>
											<Clock className="h-3 w-3 mr-1" />
											1s
										</Badge>

										<Badge
											variant="outline"
											className="bg-blue-50 text-blue-800 cursor-pointer hover:bg-blue-100"
											onClick={() => {
												setTimerInterval(1);
												setTimerUnit("minute");
											}}
										>
											<Clock className="h-3 w-3 mr-1" />
											1m
										</Badge>
										<Badge
											variant="outline"
											className="bg-blue-50 text-blue-800 cursor-pointer hover:bg-blue-100"
											onClick={() => {
												setTimerInterval(5);
												setTimerUnit("minute");
											}}
										>
											<Clock className="h-3 w-3 mr-1" />
											5m
										</Badge>
										<Badge
											variant="outline"
											className="bg-blue-50 text-blue-800 cursor-pointer hover:bg-blue-100"
											onClick={() => {
												setTimerInterval(1);
												setTimerUnit("hour");
											}}
										>
											<Clock className="h-3 w-3 mr-1" />
											1h
										</Badge>
										<Badge
											variant="outline"
											className="bg-blue-50 text-blue-800 cursor-pointer hover:bg-blue-100"
											onClick={() => {
												setTimerInterval(1);
												setTimerUnit("day");
											}}
										>
											<Clock className="h-3 w-3 mr-1" />
											1d
										</Badge>
									</div>
								</div>
							)}
						</>
					) : (
						<>
							<div className="flex flex-col gap-2">
								<Label htmlFor="updateVariable" className="text-sm font-medium">
									选择变量
								</Label>
								<Select value={variable} onValueChange={setVariable} disabled={customVariables.length === 0}>
									<SelectTrigger>
										<SelectValue placeholder={customVariables.length === 0 ? "无自定义变量" : "选择要更新的变量"} />
									</SelectTrigger>
									<SelectContent>
										{customVariables.length === 0 ? (
											<div className="px-2 py-1.5 text-sm text-muted-foreground">
												未配置自定义变量，请在策略起点配置
											</div>
										) : (
											customVariables.map((customVar: CustomVariable) => {
												const IconComponent = getVariableTypeIcon(customVar.varValueType);
												const iconColor = getVariableTypeIconColor(customVar.varValueType);

												return (
													<SelectItem key={customVar.varName} value={customVar.varName}>
														<div className="flex items-center gap-2">
															<IconComponent className={`h-4 w-4 ${iconColor}`} />
															<span>{customVar.varDisplayName}</span>
															<span className="text-xs text-muted-foreground">({customVar.varName})</span>
														</div>
													</SelectItem>
												);
											})
										)}
									</SelectContent>
								</Select>
							</div>

							{/* 触发方式 */}
							<div className="space-y-1">
								<Label className="text-sm font-medium">触发方式</Label>
								<div className="flex items-center space-x-6 pt-1">
									<div className="flex items-center space-x-2">
										<Checkbox
											id="update-condition-trigger"
											checked={updateTriggerType === "condition"}
											onCheckedChange={(checked) => {
												if (checked) {
													setUpdateTriggerType("condition");
												}
											}}
										/>
										<Label
											htmlFor="update-condition-trigger"
											className="text-sm cursor-pointer flex items-center"
										>
											<Filter className="h-3.5 w-3.5 mr-1 text-orange-500" />
											条件触发
										</Label>
									</div>
									<div className="flex items-center space-x-2">
										<Checkbox
											id="update-dataflow-trigger"
											checked={updateTriggerType === "dataflow"}
											onCheckedChange={(checked) => {
												if (checked) {
													setUpdateTriggerType("dataflow");
												}
											}}
										/>
										<Label
											htmlFor="update-dataflow-trigger"
											className="text-sm cursor-pointer flex items-center"
										>
											<Workflow className="h-3.5 w-3.5 mr-1 text-blue-500" />
											数据流触发
										</Label>
									</div>
								</div>
							</div>

							{/* 更新操作和值 - 组合在一起 */}
							{variable && (
								<div className="flex flex-col gap-2">
									<Label htmlFor="updateOperation" className="text-sm font-medium">
										{updateOperationType === "toggle" ? "更新方式" : "更新操作"}
									</Label>
									{updateOperationType === "toggle" ? (
										// toggle 模式显示选择器和说明文案
										<div className="flex flex-col gap-2">
											<Select
												value={updateOperationType}
												onValueChange={(value: UpdateOperationType) => {
													setUpdateOperationType(value);
													if (value === "toggle") {
														setUpdateValue("");
													}
												}}
											>
												<SelectTrigger>
													<SelectValue />
												</SelectTrigger>
												<SelectContent>
													{(() => {
														const selectedVar = customVariables.find(
															(v: CustomVariable) => v.varName === variable
														);
														const availableOps = getAvailableOperations(
															selectedVar?.varValueType || VariableValueType.NUMBER
														);
														return availableOps.map((op) => (
															<SelectItem key={op} value={op}>
																{getUpdateOperationLabel(op)}
															</SelectItem>
														));
													})()}
												</SelectContent>
											</Select>
											<p className="text-xs text-muted-foreground">
												如果为 True，则切换为 False；如果为 False，则切换为 True
											</p>
										</div>
									) : (
										// 其他模式显示组合控件
										(() => {
											const selectedVar = customVariables.find(
												(v: CustomVariable) => v.varName === variable
											);
											const isBooleanType = selectedVar?.varValueType === VariableValueType.BOOLEAN && updateOperationType === "set";

											return (
												<>
													{isBooleanType ? (
														// BOOLEAN 类型使用 RadioGroup，与 Select 在同一行
														<div className="flex items-center gap-16">
															<Select
																value={updateOperationType}
																onValueChange={(value: UpdateOperationType) => {
																	setUpdateOperationType(value);
																	if (value === "toggle") {
																		setUpdateValue("");
																	}
																}}
															>
																<SelectTrigger className="w-[64px]">
																	{getUpdateOperationLabel(updateOperationType)}
																</SelectTrigger>
																<SelectContent className="w-[64px] min-w-0">
																	{(() => {
																		const availableOps = getAvailableOperations(
																			selectedVar?.varValueType || VariableValueType.NUMBER
																		);
																		return availableOps.map((op) => (
																			<SelectItem key={op} value={op}>
																				{getUpdateOperationLabel(op)}
																			</SelectItem>
																		));
																	})()}
																</SelectContent>
															</Select>
															<RadioGroup
																value={updateValue || "true"}
																onValueChange={setUpdateValue}
																className="flex items-center gap-4 flex-1 pl-1"
															>
																<div className="flex items-center space-x-2">
																	<RadioGroupItem value="true" id="update-bool-true" />
																	<Label htmlFor="update-bool-true" className="cursor-pointer font-normal text-sm">
																		True
																	</Label>
																</div>
																<div className="flex items-center space-x-2">
																	<RadioGroupItem value="false" id="update-bool-false" />
																	<Label htmlFor="update-bool-false" className="cursor-pointer font-normal text-sm">
																		False
																	</Label>
																</div>
															</RadioGroup>
														</div>
													) : (
														// 非 BOOLEAN 类型使用 ButtonGroup + Input
														<ButtonGroup className="w-full">
															<Select
																value={updateOperationType}
																onValueChange={(value: UpdateOperationType) => {
																	setUpdateOperationType(value);
																	if (value === "toggle") {
																		setUpdateValue("");
																	}
																}}
															>
																<SelectTrigger className="w-[64px]">
																	{getUpdateOperationLabel(updateOperationType)}
																</SelectTrigger>
																<SelectContent className="w-[64px] min-w-0">
																	{(() => {
																		const availableOps = getAvailableOperations(
																			selectedVar?.varValueType || VariableValueType.NUMBER
																		);
																		return availableOps.map((op) => (
																			<SelectItem key={op} value={op}>
																				{getUpdateOperationLabel(op)}
																			</SelectItem>
																		));
																	})()}
																</SelectContent>
															</Select>
															<Input
																id="updateValue"
																type="text"
																value={updateValue}
																onChange={(e) => setUpdateValue(e.target.value)}
																placeholder={getUpdateOperationPlaceholder(updateOperationType)}
																className="flex-1"
															/>
														</ButtonGroup>
													)}
												</>
											);
										})()
									)}
								</div>
							)}
						</>
					)}
				</div>
				<DialogFooter>
					<Button variant="outline" onClick={() => onOpenChange(false)}>
						取消
					</Button>
					<Button
						onClick={handleSave}
						disabled={
							varOperation === "get"
								? (!variableName.trim() || isDuplicate())
								: (customVariables.length === 0 || !variable || (updateOperationType !== "toggle" && !updateValue.trim()))
						}
					>
						保存
					</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
};

export default VariableConfigDialog;
